name: Go
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        go:
          - 1.18.5
          - 1.19
    name: Build
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
          stable: ${{ !contains(matrix.go, 'beta') }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Build & Test
        run: |
          make test
