name: Go
on: [push]
jobs:
  test:
    strategy:
      matrix:
        go:
          - 1.16
          - 1.17
          - 1.18.0-beta1
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
          stable: ${{ !contains(matrix.go, 'beta') }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build & Test
        run: |
          make test
